apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data:
  CART_HOST: {{ .Values.configMap.CART_HOST }}
  CART_PORT: {{ .Values.configMap.CART_PORT }}
  USER_HOST: {{ .Values.configMap.USER_HOST }}
  USER_PORT: {{ .Values.configMap.USER_PORT }}
  AMQP_HOST: {{ .Values.configMap.AMQP_HOST }}
  AMQP_USER: {{ .Values.configMap.AMQP_USER }}
  AMQP_PASS: {{ .Values.configMap.AMQP_PASS }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: payment
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: payment
    spec:
      containers:
      - name: payment
        image: "{{ .Values.deployment.imageRepo }}:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: payment
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5                
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    component: payment
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}    # port on which service is exposed
      targetPort: 8080   # port on which payment container is listening