apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: roboshop
data:
  REDIS_URL: {{ .Values.configMap.REDIS_URL }}
  MONGO_URL: {{ .Values.configMap.MONGO_URL }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: user
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: user
    spec:
      containers:
      - name: user
        image: "{{ .Values.deployment.imageRepo }}:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: user
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5                
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    component: user
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}    # port on which service is exposed
      targetPort: 8080   # port on which user container is listening